 # Table of Contents
<div class="toc" style="margin-top: 1em;"><ul class="toc-item" id="toc-level0"></ul></div>

In [1]:
from WindPy import w
first_day='2015-01-01'
last_day='2017-08-01'
w.start()
p_wind=w.wsd('000001.SZ','close',first_day,last_day,'PriceAdj=f')

In [4]:
import sys
sys.path.append('C:\Wind\Wind.NET.Client\WindNET\bin')

In [2]:
import MDDB
import pandas as pd
import numpy as np

MDB=MDDB.MDDB()

In [3]:
f2=open('testsql2.sql')
sql2=f2.read()

In [61]:
data=pd.read_sql(sql2,MDB.conn)

In [78]:
data.head(5)

,datetime,ticker,open,high,low,close,volume,openinterest,month,year_end,rank
0,2017-03-01 01:00:00+00:00,rb1703,3800.0,3800.0,3800.0,3800.0,540,1740,03,7,15
1,2017-03-01 01:17:00+00:00,rb1703,3701.0,3701.0,3701.0,3701.0,60,1680,03,7,15
2,2017-03-01 01:39:00+00:00,rb1703,3710.0,3710.0,3710.0,3710.0,60,1620,03,7,15
3,2017-03-01 02:30:00+00:00,rb1703,3710.0,3862.0,3710.0,3862.0,60,1620,03,7,15
4,2017-03-01 03:19:00+00:00,rb1703,3800.0,3800.0,3800.0,3800.0,60,1560,03,7,15

In [76]:
import numpy as np
data['month']=data['ticker'].str.slice(start=4)
data['year_end']=data['ticker'].str.slice(start=3,stop=4)
data=data[data['year_end'].str.isnumeric()]
data['rank']=data['month'].astype(int).values+np.mod(data['year_end'].astype(int).values,2)*12

In [79]:
dp=data.pivot_table(index='datetime',columns='rank',values='open')

In [100]:
import datetime
a.ix[a.index.indexer_between_time(datetime.time(10), datetime.time(14))]

rank,1,2,3,4,5,6,7,8,9,15,16,17,18,19,20,21,22,23,24
datetime,,,,,,,,,,,,,,,,,,,
2017-03-01 10:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:01:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:02:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:03:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:04:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:05:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:06:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:07:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:08:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:09:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:10:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:11:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:12:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:13:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:14:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:15:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:16:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:17:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:18:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:19:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:20:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:21:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:22:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:23:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:24:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:25:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:26:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:27:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:28:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01 10:29:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-09-20 13:31:00+00:00,3769.0,NaN,NaN,NaN,3638.0,NaN,NaN,NaN,3600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4055.0,NaN,NaN
2017-09-20 13:32:00+00:00,3769.0,NaN,NaN,3702.0,3636.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4052.0,NaN,NaN
2017-09-20 13:33:00+00:00,3769.0,NaN,NaN,NaN,3635.0,3605.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4053.0,NaN,NaN
2017-09-20 13:34:00+00:00,3775.0,NaN,NaN,NaN,3639.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4054.0,NaN,NaN
2017-09-20 13:35:00+00:00,3773.0,NaN,NaN,NaN,3637.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4055.0,NaN,NaN
2017-09-20 13:36:00+00:00,3765.0,NaN,NaN,NaN,3633.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4053.0,NaN,NaN
2017-09-20 13:37:00+00:00,3764.0,NaN,NaN,NaN,3632.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4053.0,NaN,NaN
2017-09-20 13:38:00+00:00,3768.0,NaN,NaN,NaN,3636.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4047.0,NaN,NaN
2017-09-20 13:39:00+00:00,3770.0,NaN,NaN,NaN,3638.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4049.0,NaN,NaN
2017-09-20 13:40:00+00:00,3770.0,NaN,NaN,NaN,3635.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4049.0,NaN,NaN
2017-09-20 13:41:00+00:00,3766.0,NaN,NaN,NaN,3633.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4045.0,NaN,NaN
2017-09-20 13:42:00+00:00,3767.0,NaN,NaN,NaN,3636.0,3604.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4048.0,NaN,NaN
2017-09-20 13:43:00+00:00,3770.0,NaN,NaN,NaN,3639.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4048.0,NaN,NaN
2017-09-20 13:44:00+00:00,3767.0,NaN,NaN,NaN,3635.0,NaN,3601.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4047.0,NaN,NaN
2017-09-20 13:45:00+00:00,3764.0,NaN,NaN,3684.0,3633.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4044.0,NaN,NaN
2017-09-20 13:46:00+00:00,3763.0,NaN,NaN,NaN,3632.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4041.0,NaN,NaN
2017-09-20 13:47:00+00:00,3762.0,NaN,NaN,NaN,3634.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4044.0,NaN,NaN
2017-09-20 13:48:00+00:00,3763.0,NaN,NaN,NaN,3633.0,NaN,NaN,3609.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4045.0,NaN,NaN
2017-09-20 13:49:00+00:00,3766.0,NaN,NaN,NaN,3635.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4046.0,NaN,NaN
2017-09-20 13:50:00+00:00,3769.0,3688.0,NaN,NaN,3637.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4049.0,NaN,NaN
2017-09-20 13:51:00+00:00,3774.0,NaN,NaN,NaN,3641.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4050.0,NaN,NaN
2017-09-20 13:52:00+00:00,3769.0,3689.0,NaN,3684.0,3638.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4052.0,NaN,NaN
2017-09-20 13:53:00+00:00,3769.0,3689.0,NaN,NaN,3637.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4053.0,NaN,NaN
2017-09-20 13:54:00+00:00,3770.0,NaN,NaN,NaN,3637.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4052.0,NaN,NaN
2017-09-20 13:55:00+00:00,3770.0,NaN,NaN,NaN,3637.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4050.0,NaN,NaN
2017-09-20 13:56:00+00:00,3769.0,NaN,NaN,NaN,3636.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4052.0,NaN,NaN
2017-09-20 13:57:00+00:00,3767.0,NaN,NaN,NaN,3633.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4050.0,NaN,NaN
2017-09-20 13:58:00+00:00,3762.0,NaN,NaN,NaN,3631.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4048.0,NaN,NaN
2017-09-20 13:59:00+00:00,3763.0,NaN,NaN,NaN,3633.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3946.0
2017-09-20 14:00:00+00:00,3766.0,NaN,NaN,NaN,3635.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4047.0,NaN,NaN

In [101]:
b=a.index.indexer_between_time(datetime.time(10), datetime.time(14))

In [102]:
b

array([   540,    541,    542, ..., 293098, 293099, 293100], dtype=int64)

In [84]:
a=dp.resample('1min').agg('last')

In [85]:
a.shape

(294121, 19)

In [86]:
dp.shape

(48071, 19)

In [81]:
help(dp.resample)

Help on method resample in module pandas.core.generic:

resample(rule, how=None, axis=0, fill_method=None, closed=None, label=None, convention='start', kind=None, loffset=None, limit=None, base=0, on=None, level=None) method of pandas.core.frame.DataFrame instance
    Convenience method for frequency conversion and resampling of time
    series.  Object must have a datetime-like index (DatetimeIndex,
    PeriodIndex, or TimedeltaIndex), or pass datetime-like values
    to the on or level keyword.

    Parameters
    ----------
    rule : string
        the offset string or object representing target conversion
    axis : int, optional, default 0
    closed : {'right', 'left'}
        Which side of bin interval is closed
    label : {'right', 'left'}
        Which bin edge label to label bucket with
    convention : {'start', 'end', 's', 'e'}
    loffset : timedelta
        Adjust the resampled time labels
    base : int, default 0
        For frequencies that evenly subdivide 1 day, the "origin" of the
        aggregated intervals. For example, for '5min' frequency, base could
        range from 0 through 4. Defaults to 0
    on : string, optional
        For a DataFrame, column to use instead of index for resampling.
        Column must be datetime-like.

        .. versionadded:: 0.19.0

    level : string or int, optional
        For a MultiIndex, level (name or number) to use for
        resampling.  Level must be datetime-like.

        .. versionadded:: 0.19.0

    Notes
    -----
    To learn more about the offset strings, please see `this link
    <http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases>`__.

    Examples
    --------

    Start by creating a series with 9 one minute timestamps.

    >>> index = pd.date_range('1/1/2000', periods=9, freq='T')
    >>> series = pd.Series(range(9), index=index)
    >>> series
    2000-01-01 00:00:00    0
    2000-01-01 00:01:00    1
    2000-01-01 00:02:00    2
    2000-01-01 00:03:00    3
    2000-01-01 00:04:00    4
    2000-01-01 00:05:00    5
    2000-01-01 00:06:00    6
    2000-01-01 00:07:00    7
    2000-01-01 00:08:00    8
    Freq: T, dtype: int64

    Downsample the series into 3 minute bins and sum the values
    of the timestamps falling into a bin.

    >>> series.resample('3T').sum()
    2000-01-01 00:00:00     3
    2000-01-01 00:03:00    12
    2000-01-01 00:06:00    21
    Freq: 3T, dtype: int64

    Downsample the series into 3 minute bins as above, but label each
    bin using the right edge instead of the left. Please note that the
    value in the bucket used as the label is not included in the bucket,
    which it labels. For example, in the original series the
    bucket ``2000-01-01 00:03:00`` contains the value 3, but the summed
    value in the resampled bucket with the label``2000-01-01 00:03:00``
    does not include 3 (if it did, the summed value would be 6, not 3).
    To include this value close the right side of the bin interval as
    illustrated in the example below this one.

    >>> series.resample('3T', label='right').sum()
    2000-01-01 00:03:00     3
    2000-01-01 00:06:00    12
    2000-01-01 00:09:00    21
    Freq: 3T, dtype: int64

    Downsample the series into 3 minute bins as above, but close the right
    side of the bin interval.

    >>> series.resample('3T', label='right', closed='right').sum()
    2000-01-01 00:00:00     0
    2000-01-01 00:03:00     6
    2000-01-01 00:06:00    15
    2000-01-01 00:09:00    15
    Freq: 3T, dtype: int64

    Upsample the series into 30 second bins.

    >>> series.resample('30S').asfreq()[0:5] #select first 5 rows
    2000-01-01 00:00:00   0.0
    2000-01-01 00:00:30   NaN
    2000-01-01 00:01:00   1.0
    2000-01-01 00:01:30   NaN
    2000-01-01 00:02:00   2.0
    Freq: 30S, dtype: float64

    Upsample the series into 30 second bins and fill the ``NaN``
    values using the ``pad`` method.

    >>> series.resample('30S').pad()[0:5]
    2000-01-01 00:00:00    0
    2000-01-01 00:00:30    0
    2000-01-01 00:01:00    1
    2000-01-01 00:01:30    1
    2000-01-01 00:02:00    2
    Freq: 30S, dtype: int64

    Upsample the series into 30 second bins and fill the
    ``NaN`` values using the ``bfill`` method.

    >>> series.resample('30S').bfill()[0:5]
    2000-01-01 00:00:00    0
    2000-01-01 00:00:30    1
    2000-01-01 00:01:00    1
    2000-01-01 00:01:30    2
    2000-01-01 00:02:00    2
    Freq: 30S, dtype: int64

    Pass a custom function via ``apply``

    >>> def custom_resampler(array_like):
    ...     return np.sum(array_like)+5

    >>> series.resample('3T').apply(custom_resampler)
    2000-01-01 00:00:00     8
    2000-01-01 00:03:00    17
    2000-01-01 00:06:00    26
    Freq: 3T, dtype: int64

    For DataFrame objects, the keyword ``on`` can be used to specify the
    column instead of the index for resampling.

    >>> df = pd.DataFrame(data=9*[range(4)], columns=['a', 'b', 'c', 'd'])
    >>> df['time'] = pd.date_range('1/1/2000', periods=9, freq='T')
    >>> df.resample('3T', on='time').sum()
                         a  b  c  d
    time
    2000-01-01 00:00:00  0  3  6  9
    2000-01-01 00:03:00  0  3  6  9
    2000-01-01 00:06:00  0  3  6  9

    For a DataFrame with MultiIndex, the keyword ``level`` can be used to
    specify on level the resampling needs to take place.

    >>> time = pd.date_range('1/1/2000', periods=5, freq='T')
    >>> df2 = pd.DataFrame(data=10*[range(4)],
                           columns=['a', 'b', 'c', 'd'],
                           index=pd.MultiIndex.from_product([time, [1, 2]])
                           )
    >>> df2.resample('3T', level=0).sum()
                         a  b   c   d
    2000-01-01 00:00:00  0  6  12  18
    2000-01-01 00:03:00  0  4   8  12

In [11]:
help(a.str.slice)

Help on method slice in module pandas.core.strings:

slice(start=None, stop=None, step=None) method of pandas.core.strings.StringMethods instance
    Slice substrings from each element in the Series/Index

    Parameters
    ----------
    start : int or None
    stop : int or None
    step : int or None

    Returns
    -------
    sliced : Series/Index of objects

In [6]:
data.shape

(208913, 8)

In [16]:
f1=open('testsql.sql')
sql1=f1.read()

In [18]:
data1=pd.read_sql(sql1,MDB.conn)

In [19]:
data1.head(5)

,date,ticker,open,high,low,close,settle,volume,openinterest
0,2017-02-20,a1703,4232.0,4232.0,4200.0,4200.0,4217.0,18,1246
1,2017-02-20,a1705,4230.0,4251.0,4214.0,4236.0,4235.0,130384,164596
2,2017-02-20,a1707,0.0,0.0,0.0,4253.0,4253.0,0,28
3,2017-02-20,a1709,4221.0,4221.0,4180.0,4200.0,4198.0,19624,49522
4,2017-02-20,a1711,4198.0,4198.0,4198.0,4198.0,4198.0,2,4

In [2]:
import matlab